"""Hand-authored creature tiles (cd-e17.7).

PLACEHOLDER set - front-facing, one 16x16 tile each (ART.md sec1).
"""
from __future__ import annotations

from tilelib import Tile

L = {
    ".": None,
    " ": None,
    "k": "ink_black",
    "w": "off_white",
    "b": "blood",
    "g": "moss_mid",
    "G": "moss_light",
    "d": "moss_dark",
    "s": "neutral_light",
    "y": "gold",
    "r": "blood_bright",
    "n": "dirt_mid",
    "p": "arcane_dark",
    "P": "arcane",
}

SLIME = """
................
................
................
.....ddddd......
...ddgggggdd....
..dggggggggdd...
..dgGggkggGgd...
..dgggkwkgggd...
.dgggggkggggd...
.dggggggggggd...
.dggggggggggd...
..dgggggggggd...
..ddgggggggdd...
...dddddddddd...
................
................
"""

RAT = """
................
................
............kk..
...........knnk.
..kk......knnnk.
.knnk....knnnnk.
.knnnkkkknnnnk..
.knnnnnnnnnnk...
..knnnnnnnnk....
..knwnnnnwnk....
..knnnkknnnk....
...knnnnnnk.....
....kknnkk......
......kk........
................
................
"""

SKELETON = """
......kkkk......
.....kwwwwk.....
.....wkwwkw.....
.....wwwwww.....
.....kwwwwk.....
......kwwk......
....kwwwwwwk....
...kw.wwww.wk...
...kwkwwwwkwk...
...k.kwwww.k.k..
.....wwwwww.....
.....ww..ww.....
....kwk..kwk....
....kwk..kwk....
....kk....kk....
................
"""

BAT = """
................
................
.kk..........kk.
kppk........kppk
kpppk......kpppk
kppppkk..kkppppk
kpppppkkkkppppk.
.kppppwppwpppk..
..kpppwkwkpppk..
...kppppppppk...
....kkppppkk....
......kkkk......
................
................
................
................
"""

GOBLIN = """
................
.....k....k.....
.....kk..kk.....
....kggggggk....
...kggggggggk...
...kgwgkkgwgk...
...kggkrrkggk...
...kgggrrgggk...
....kggggggk....
...kddgggddk....
..kd.kgggg.dk...
.....kk..kk.....
....kbb..kbb....
....kk....kk....
................
................
"""


def build(pal) -> list[Tile]:
    src = [
        ("slime", SLIME),
        ("rat", RAT),
        ("skeleton", SKELETON),
        ("bat", BAT),
        ("goblin", GOBLIN),
    ]
    return [Tile.from_ascii(n, a, L, pal) for n, a in src]
