"""Hand-authored hero tiles (cd-e17.6).

PLACEHOLDER set - 3 classes, front-facing, ~12px figure in a 16px cell
(ART.md sec1, sec6).
"""
from __future__ import annotations

from tilelib import Tile

L = {
    ".": None,
    " ": None,
    "k": "ink_black",
    "w": "off_white",
    "f": "flesh",
    "F": "flesh_shadow",
    "s": "stone_mid",
    "S": "stone_light",
    "r": "blood",
    "b": "water",
    "B": "water_light",
    "g": "gold",
    "p": "arcane",
    "P": "arcane_bright",
    "n": "wood_mid",
    "m": "moss_mid",
}

WARRIOR = """
.....kkkk.......
....kSSSSk......
....kSwwSk......
....kSffSk......
....kFffFk......
...kkkffkkk.....
..krrsssrrk.....
..krsssssrk.....
.gkrsssssrkg....
.gkkrsssrkkg....
.g.kFf.fFk.g....
...kFf.fFk......
...kn...nk......
...kn...nk......
..kk.....kk.....
................
"""

MAGE = """
......kk........
.....kppk.......
....kppppk......
...kppppppk.....
....kkffkk......
.....kffk.......
....kpFfpk......
...kppffppk.....
..kpppffpppk....
..kp.pppp.pk....
..kn.pppp.nk....
.gg..kppk..gg...
....kFf.fFk.....
....kn...nk.....
...kk.....kk....
................
"""

ROGUE = """
....kkkk........
...kmmmmk.......
...kmwwmk.......
...kmffmk.......
...kFffFk.......
..kkkffkkk......
..kmnnnnnmk.....
..kmnnnnnmk.....
.kkmnnnnnmkk....
.b.kmnnnmk.b....
.b.kFf.fFk.b....
...kFf.fFk......
...kn...nk......
...kn...nk......
..kk.....kk.....
................
"""


def build(pal) -> list[Tile]:
    src = [
        ("warrior", WARRIOR),
        ("mage", MAGE),
        ("rogue", ROGUE),
    ]
    return [Tile.from_ascii(n, a, L, pal) for n, a in src]
