"""Hand-authored object / item tiles (cd-e17.8).

PLACEHOLDER set - a few items to exercise the pipeline and preview.
Legend chars are per-file; values are master-palette colour names
(None -> transparent index 0).
"""
from __future__ import annotations

from tilelib import Tile

L = {
    ".": None,
    " ": None,
    "k": "ink_black",
    "w": "off_white",
    "r": "blood",
    "R": "blood_bright",
    "g": "gold",
    "G": "gold_light",
    "b": "bronze",
    "m": "water",
    "M": "water_light",
    "p": "arcane",
    "n": "wood_mid",
    "d": "wood_dark",
    "s": "stone_mid",
}

POTION_RED = """
......kkkk......
......kwwk......
......kwwk......
.....kkwwkk.....
....kwRRRRwk....
...kwRRRRRRwk...
...kRRRRRRRRk...
...kRRRRRRRRk...
...kRRRRRRRRk...
...kRRwwwwRRk...
...kRRRRRRRRk...
...kkRRRRRRkk...
....kkkkkkkk....
................
................
................
"""

POTION_BLUE = """
......kkkk......
......kwwk......
......kwwk......
.....kkwwkk.....
....kwMMMMwk....
...kwMMMMMMwk...
...kMMMMMMMMk...
...kMMmmmmMMk...
...kMmmmmmmMk...
...kMmmmmmmMk...
...kMMmmmmMMk...
...kkMMMMMMkk...
....kkkkkkkk....
................
................
................
"""

COIN = """
................
................
.....kkkkkk.....
...kkGGGGGGkk...
..kGGggggggGGk..
..kGgggwwgggGk..
..kGggwggwggGk..
..kGggwggwggGk..
..kGggwggwggGk..
..kGggwggwggGk..
..kGgggwwgggGk..
..kGGggggggGGk..
...kkGGGGGGkk...
.....kkkkkk.....
................
................
"""

SWORD = """
............kwwk
...........kMMwk
..........kMMwk.
.........kMMwk..
........kMMwk...
.......kMMwk....
......kMMwk.....
.....kMMwk......
....kMMwk.......
...kMMwk........
..kgwMwgk.......
.kggwwggk.......
..kkgngkk.......
....knnk........
....knnk........
.....kk.........
"""

CHEST = """
................
....kkkkkkkk....
...kbbbbbbbbk...
..kbnnnnnnnnbk..
..kbnddnnddnbk..
..kbnnnnnnnnbk..
..kbbbbggbbbbk..
..kbnnngGgnnnbk.
..kbnnngGgnnnbk.
..kbnddnnnnddbk.
..kbnnnnnnnnnbk.
..kbbbbbbbbbbbk.
...kkkkkkkkkkk..
................
................
................
"""

SCROLL = """
................
....wwwwwwww....
...wnwwwwwwnw...
...wnwwwwwwnw...
...wnwkkkkwnw...
...wnwwwwwwnw...
...wnwkkkkwnw...
...wnwwwwwwnw...
...wnwkkkkwnw...
...wnwwwwwwnw...
...wnwkkkkwnw...
...wnwwwwwwnw...
...wnwwwwwwnw...
....wwwwwwww....
................
................
"""

CORPSE = """
................
................
................
................
.....ww...ww....
....wssw.wssw...
....wsssssssw...
...wsswwwwwssw..
...wswkwwkwsw...
...wsswwwwwssw..
....wsssssssw...
.....wwsssww....
.......www......
................
................
................
"""


def build(pal) -> list[Tile]:
    src = [
        ("potion_red", POTION_RED),
        ("potion_blue", POTION_BLUE),
        ("coin", COIN),
        ("sword", SWORD),
        ("chest", CHEST),
        ("scroll", SCROLL),
        ("corpse", CORPSE),
    ]
    return [Tile.from_ascii(n, a, L, pal) for n, a in src]
