"""Ch7 master palette - generated by tools/build_palette.py (cd-e17.3).

Do not edit by hand.  Edit RAMPS in build_palette.py and re-run.
Capacity 64; indices 0..15 are frozen core.
"""

CAPACITY = 64
CORE_SIZE = 16

# index 0 = transparent, authored as 0xFF00FF magenta
PAL = (
    (255,   0, 255),  #  0 transparent [core]
    ( 20,  12,  28),  #  1 ink_black [core]
    ( 43,  39,  51),  #  2 neutral_dark [core]
    ( 74,  70,  88),  #  3 neutral_mid [core]
    (138, 134, 152),  #  4 neutral_light [core]
    (232, 224, 208),  #  5 off_white [core]
    ( 51,  64,  76),  #  6 stone_dark [core]
    ( 92, 113, 130),  #  7 stone_mid [core]
    (138, 160, 176),  #  8 stone_light [core]
    ( 42,  30,  22),  #  9 dirt_darkest [core]
    ( 62,  46,  32),  # 10 dirt_dark [core]
    ( 90,  67,  48),  # 11 dirt_mid [core]
    (138, 107,  74),  # 12 dirt_light [core]
    ( 69,  48,  31),  # 13 wood_dark [core]
    (122,  82,  48),  # 14 wood_mid [core]
    (168, 122,  69),  # 15 wood_light [core]
    ( 30,  42,  22),  # 16 moss_darkest [moss]
    ( 44,  58,  30),  # 17 moss_dark [moss]
    ( 79, 107,  44),  # 18 moss_mid [moss]
    (134, 166,  62),  # 19 moss_light [moss]
    ( 58,  20,  20),  # 20 blood_darkest [blood]
    ( 94,  29,  29),  # 21 blood_dark [blood]
    (168,  50,  46),  # 22 blood [blood]
    (216,  80,  58),  # 23 blood_bright [blood]
    ( 74,  50,  18),  # 24 bronze_dark [gold]
    (122,  83,  32),  # 25 bronze [gold]
    (216, 169,  60),  # 26 gold [gold]
    (240, 214, 122),  # 27 gold_light [gold]
    ( 22,  40,  63),  # 28 water_darkest [water]
    ( 30,  58,  92),  # 29 deep_water [water]
    ( 62, 119, 176),  # 30 water [water]
    (143, 200, 222),  # 31 water_light [water]
    ( 42,  30,  66),  # 32 arcane_dark [arcane]
    ( 94,  58, 148),  # 33 arcane [arcane]
    (155, 111, 208),  # 34 arcane_bright [arcane]
    (168,  69,  28),  # 35 fire_dark [fire]
    (232, 128,  44),  # 36 fire [fire]
    (244, 194,  74),  # 37 fire_bright [fire]
    (154, 107,  78),  # 38 flesh_shadow [flesh]
    (200, 150, 110),  # 39 flesh [flesh]
    ( 18,  13,   9),  # 40 dirt_darkest_dim [fog_dim]
    ( 27,  20,  14),  # 41 dirt_dark_dim [fog_dim]
    ( 40,  30,  21),  # 42 dirt_mid_dim [fog_dim]
    ( 62,  48,  33),  # 43 dirt_light_dim [fog_dim]
    ( 22,  28,  34),  # 44 stone_dark_dim [fog_dim]
    ( 41,  50,  58),  # 45 stone_mid_dim [fog_dim]
    ( 62,  72,  79),  # 46 stone_light_dim [fog_dim]
    ( 35,  48,  19),  # 47 moss_mid_dim [fog_dim]
    ( 19,  17,  22),  # 48 neutral_dark_dim [fog_dim]
    ( 33,  31,  39),  # 49 neutral_mid_dim [fog_dim]
    ( 62,  60,  68),  # 50 neutral_light_dim [fog_dim]
    (  9,   5,  12),  # 51 ink_black_dim [fog_dim]
    (  9,  18,  28),  # 52 water_darkest_dim [fog_dim]
    ( 13,  26,  41),  # 53 deep_water_dim [fog_dim]
    ( 27,  53,  79),  # 54 water_dim [fog_dim]
    ( 64,  90,  99),  # 55 water_light_dim [fog_dim]
    (104, 100,  93),  # 56 off_white_dim [fog_dim]
)

IDX = {
    'transparent': 0,
    'ink_black': 1,
    'neutral_dark': 2,
    'neutral_mid': 3,
    'neutral_light': 4,
    'off_white': 5,
    'stone_dark': 6,
    'stone_mid': 7,
    'stone_light': 8,
    'dirt_darkest': 9,
    'dirt_dark': 10,
    'dirt_mid': 11,
    'dirt_light': 12,
    'wood_dark': 13,
    'wood_mid': 14,
    'wood_light': 15,
    'moss_darkest': 16,
    'moss_dark': 17,
    'moss_mid': 18,
    'moss_light': 19,
    'blood_darkest': 20,
    'blood_dark': 21,
    'blood': 22,
    'blood_bright': 23,
    'bronze_dark': 24,
    'bronze': 25,
    'gold': 26,
    'gold_light': 27,
    'water_darkest': 28,
    'deep_water': 29,
    'water': 30,
    'water_light': 31,
    'arcane_dark': 32,
    'arcane': 33,
    'arcane_bright': 34,
    'fire_dark': 35,
    'fire': 36,
    'fire_bright': 37,
    'flesh_shadow': 38,
    'flesh': 39,
    'dirt_darkest_dim': 40,
    'dirt_dark_dim': 41,
    'dirt_mid_dim': 42,
    'dirt_light_dim': 43,
    'stone_dark_dim': 44,
    'stone_mid_dim': 45,
    'stone_light_dim': 46,
    'moss_mid_dim': 47,
    'neutral_dark_dim': 48,
    'neutral_mid_dim': 49,
    'neutral_light_dim': 50,
    'ink_black_dim': 51,
    'water_darkest_dim': 52,
    'deep_water_dim': 53,
    'water_dim': 54,
    'water_light_dim': 55,
    'off_white_dim': 56,
}
